apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ghcr.io/sajjadkhan-academy/fastapi-cli-83909
    newTag: bootstrap

namespace: apps

commonLabels:
  app: fastapi-cli-83909
  environment: dev
