apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: single-store-test-2
  labels:
    app: single-store-test-2
    backstage.io/kubernetes-id: single-store-test-2
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
spec:
  ingressClassName: nginx
  rules:
    - host: single-store-test-2.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: single-store-test-2
                port:
                  number: 80
