apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: new-test-m-argo
  labels:
    app: new-test-m-argo
    backstage.io/kubernetes-id: new-test-m-argo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: new-test-m-argo
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
