apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: test-monitoring-prometnues
  labels:
    app: test-monitoring-prometnues
    backstage.io/kubernetes-id: test-monitoring-prometnues
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test-monitoring-prometnues
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
