apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: testing-app-3
  labels:
    app: testing-app-3
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
spec:
  ingressClassName: nginx
  rules:
    - host: testing-app-3.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: testing-app-3
                port:
                  number: 80
