apiVersion: v1
kind: Service
metadata:
  name: testing-app-3
  labels:
    app: testing-app-3
spec:
  type: ClusterIP
  selector:
    app: testing-app-3
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
