apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-test-sajjadkhan-33
  labels:
    app: my-test-sajjadkhan-33
    backstage.io/kubernetes-id: my-test-sajjadkhan-33
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-test-sajjadkhan-33
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
