apiVersion: v1
kind: Service
metadata:
  name: my-test-sajjadkhan-33
  labels:
    app: my-test-sajjadkhan-33
    backstage.io/kubernetes-id: my-test-sajjadkhan-33
spec:
  type: ClusterIP
  selector:
    app: my-test-sajjadkhan-33
  ports:
    - name: http
      port: 80
      targetPort: 8087
      protocol: TCP
