apiVersion: v1
kind: Service
metadata:
  name: test-service-a
  labels:
    app: test-service-a
spec:
  type: ClusterIP
  selector:
    app: test-service-a
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
