apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microservice-test-7878
  labels:
    app: microservice-test-7878
    backstage.io/kubernetes-id: microservice-test-7878
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
spec:
  ingressClassName: nginx
  rules:
    - host: microservice-test-7878.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: microservice-test-7878
                port:
                  number: 80
