apiVersion: v1
kind: Service
metadata:
  name: microservice-test-7878
  labels:
    app: microservice-test-7878
    backstage.io/kubernetes-id: microservice-test-7878
spec:
  type: ClusterIP
  selector:
    app: microservice-test-7878
  ports:
    - name: http
      port: 80
      targetPort: 7068
      protocol: TCP
