apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: ghcr.io/sajjadkhan-academy/sajjdkhan-9090
    newTag: f85cb58c82a63937b10633c6647690325a602ced
namespace: apps
commonLabels:
  app: sajjdkhan-9090
  environment: dev
