apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ghcr.io/sajjadkhan-academy/test-service-abc
    newTag: latest

namespace: apps

commonLabels:
  app: test-service-abc
  environment: dev
