apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: new-microservice-team-a-dev
  namespace: argocd
  labels:
    app: new-microservice-team-a
    environment: dev
spec:
  project: default
  source:
    repoURL: https://github.com/sajjadkhan12/argocd-centralized-repo-idp.git
    targetRevision: main
    path: apps/new-microservice-team-a/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: new-microservice-team-a
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
