apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-service-a-dev
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: service=
    argocd-image-updater.argoproj.io/service.pull-secret: secret:argocd/ghcr-pull-secret
    argocd-image-updater.argoproj.io/service.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
    app: test-service-a
    environment: dev
spec:
  project: default
  source:
    repoURL: https://github.com/sajjadkhan-academy/argocd-centralized-repo-idp.git
    targetRevision: main
    path: apps/test-service-a/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
