apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: new-microservice-team-a
  labels:
    app: new-microservice-team-a
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
spec:
  ingressClassName: nginx
  rules:
    - host: new-microservice-team-a.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: new-microservice-team-a
                port:
                  number: 80
