apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: single-store-test
  labels:
    app: single-store-test
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: single-store-test
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
