apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: single-store-test
  labels:
    app: single-store-test
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
spec:
  ingressClassName: nginx
  rules:
    - host: single-store-test.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: single-store-test
                port:
                  number: 80
