apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: ghcr.io/sajjadkhan-academy/test-monitoring-prometnues
    newTag: 90a2209bf51ce84ba294e19f69676d9629595a9f
namespace: apps
commonLabels:
  app: test-monitoring-prometnues
  environment: dev
