apiVersion: v1
kind: Service
metadata:
  name: fastapi-cli-83909
  labels:
    app: fastapi-cli-83909
    backstage.io/kubernetes-id: fastapi-cli-83909
spec:
  type: ClusterIP
  selector:
    app: fastapi-cli-83909
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
