apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ghcr.io/sajjadkhan-academy/testing-543553453
    newTag: bootstrap

namespace: apps

commonLabels:
  app: testing-543553453
  environment: dev
