apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ghcr.io/sajjadkhan-academy/my-test-sajjadkhan-33
    newTag: latest

namespace: apps

commonLabels:
  app: my-test-sajjadkhan-33
  environment: dev
