apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: testing-543553453
  labels:
    app: testing-543553453
    backstage.io/kubernetes-id: testing-543553453
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: testing-543553453
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
