apiVersion: v1
kind: Service
metadata:
  name: testing-543553453
  labels:
    app: testing-543553453
    backstage.io/kubernetes-id: testing-543553453
spec:
  type: ClusterIP
  selector:
    app: testing-543553453
  ports:
    - name: http
      port: 80
      targetPort: 8068
      protocol: TCP
