apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ghcr.io/sajjadkhan-academy/new-microservice-team-b
    newTag: latest

namespace: new-microservice-team-b

commonLabels:
  app: new-microservice-team-b
  environment: dev
