apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: ghcr.io/sajjadkhan-academy/new-microservice-team-b
    newTag: 4c26acdf7b9e4576f00c17dded564f5e502467ca
namespace: new-microservice-team-b
commonLabels:
  app: new-microservice-team-b
  environment: dev
