apiVersion: v1
kind: Service
metadata:
  name: python-fastapi-test-9090
  labels:
    app: python-fastapi-test-9090
    backstage.io/kubernetes-id: python-fastapi-test-9090
spec:
  type: ClusterIP
  selector:
    app: python-fastapi-test-9090
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
