apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ms-team-c
  labels:
    app: ms-team-c
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
spec:
  ingressClassName: nginx
  rules:
    - host: ms-team-c.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ms-team-c
                port:
                  number: 80
