apiVersion: v1
kind: Service
metadata:
  name: ms-team-c
  labels:
    app: ms-team-c
spec:
  type: ClusterIP
  selector:
    app: ms-team-c
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
