apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: ghcr.io/sajjadkhan-academy/new-microservice-team-a
    newTag: 00552d5b84de400a4b6bbc72dfc50a517e6cdf09
namespace: new-microservice-team-a
commonLabels:
  app: new-microservice-team-a
  environment: dev
