apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-fastapi-test
  labels:
    app: test-fastapi-test
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
spec:
  ingressClassName: nginx
  rules:
    - host: test-fastapi-test.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: test-fastapi-test
                port:
                  number: 80
