apiVersion: v1
kind: Service
metadata:
  name: test-fastapi-test
  labels:
    app: test-fastapi-test
spec:
  type: ClusterIP
  selector:
    app: test-fastapi-test
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
