apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ghcr.io/sajjadkhan-academy/ecommerce-test-service
    newTag: bootstrap

namespace: apps

commonLabels:
  app: ecommerce-test-service
  environment: dev
