apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: ghcr.io/sajjadkhan-academy/ecommerce-test-service
    newTag: ed74f05bc325e6e7aeccdf3008a9074167d20291
namespace: apps
commonLabels:
  app: ecommerce-test-service
  environment: dev
