apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ghcr.io/sajjadkhan-academy/testing-app-3

namespace: apps

commonLabels:
  app: testing-app-3
  environment: dev
