apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ghcr.io/sajjadkhan-academy/python-fastapi-test-9090

namespace: apps

commonLabels:
  app: python-fastapi-test-9090
  environment: dev
