apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ghcr.io/sajjadkhan-academy/new-test-m-argo

namespace: apps

commonLabels:
  app: new-test-m-argo
  environment: dev
