apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: ghcr.io/sajjadkhan-academy/new-test-m-argo
    newTag: c50ea8de6509e1d2846c3d750b2c3ecf154ce20d
namespace: apps
commonLabels:
  app: new-test-m-argo
  environment: dev
