apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: ghcr.io/sajjadkhan-academy/new-test-m-argo
    newTag: ed2ee6da7adcc083a18abe1f1c0e9ca683ebb2ec
namespace: apps
commonLabels:
  app: new-test-m-argo
  environment: dev
